# SPDX-FileCopyrightText: 2023 Technology Innovation Institute (TII)
#
# SPDX-License-Identifier: Apache-2.0

name: CPE dictionary update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "5 2 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Update CPE dictionary
      run: ./update-cpedict.sh
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic CPE dictionary update
